baseURL = 'https://blog.lynkify.in/'
languageCode = 'en-us'
title = 'Lynkify Blog'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 20

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 10

[taxonomies]
tag = "tags"
author = "authors"
category = "categories"

# paginate = 2

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
